### ISSUE TITLE
SystemError: unknown opcode

### ISSUE THREAD

**Issue by XYZ-916** [RanSuLab/RAUNet-tumor-segmentation#1]
When testing the trained model, I got the error as follows:
      SystemError: unknown opcode
as keras.models.load_model(model_file, custom_objects=custom_objects, compile=False)

Any suggestions to the problem？
Thank you~

**Comment by qgking** [comment]
Why do you want to load custom layer? If you want to vis the layer, I think the code is in the plot_3d.py in the plot_feature_map function.
When training, save the model by calling "model.save(path)" 
In the test phase, just call  load_model(path).
This code is for our paper, which is under review, pls, cite our paper if you use.
"RA-UNet: A hybrid deep attention-aware network to extract liver and tumor in CT scans"

**Comment by qgking** [comment]
@XYZ916829 
Why do you want to load custom layer? If you want to vis the layer, I think the code is in the plot_3d.py in the plot_feature_map function.
When training, save the model by calling "model.save(path)"
In the test phase, just call load_model(path).
This code is for our paper, which is under review, pls, cite our paper if you use.
"RA-UNet: A hybrid deep attention-aware network to extract liver and tumor in CT scans"
