### ISSUE TITLE
some confusion about processing.py

### ISSUE THREAD

**Issue by zz10001** [RanSuLab/RAUNet-tumor-segmentation#3]
Hi,
Thanks for your great work,I have some trouble when i read the processing.py.In your papar(page7 G. Extraction of tumors based on RA-UNet-II),you say
![image](https://user-images.githubusercontent.com/39954774/67258194-0cf92c80-f4c2-11e9-8cd9-9996fdc699c5.png)
but in processing.py(line 41),you use interpolate. I don't know how to understand it, can you explain it.
Much obligated for your help!

**Comment by qgking** [comment]
@zz10001 The interpolation op is in the "if" statement (line 34), which is for the liver (RA-UNet-1). Set the "liver_patch" to false, if u want to extract tumor patches. Thank you

**Comment by zz10001** [comment]
Thanks for your help! I misunderstand it

**Comment by zz10001** [comment]
Sorry to bother you again, I noticed that in you in**ferlivertumor.py** **def liver_tumor_inference()**,the patch will have overlap when it start to predict like this 
![image](https://user-images.githubusercontent.com/39954774/69959507-46ea3380-1542-11ea-8fa9-d17752542714.png)
![image](https://user-images.githubusercontent.com/39954774/69959579-7d27b300-1542-11ea-90c3-aaf679febd69.png)

As see above, the first patch will be [0:64, : , :], and second will be [32:96, :, :], it have some overlap, is it all right to predict? thanks for your help!
